spring:
  application:
    name: task-manager

  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5433/taskmanagerdb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: "replace-this-with-a-long-random-base64-secret-min-256-bits"
  expiration-ms: 3600000   # 1 hour